### ISSUE TITLE
Building under GCC 4.6.3 fails

### ISSUE THREAD

**Issue by keiranmraine** [jmarshall/cansam#1]
cansam builds fine under gcc 4.3.2 (Debian lenny) but while attempting to build on a precise box with 4.6.3 we've found several issues.

``` c++
#include <stddef.h>
```

Needs to be added to several files (cansam/sam/header.h, cansam/sam/alignment.h)

Once this was resolved other more opaque issues have arisen.  As I have very little C++ knowledge I'd really appreciate some help.

```
> make
g++ -Wall -Wextra -g -O2 -I.   -c -o lib/alignment.o lib/alignment.cpp
In file included from lib/alignment.cpp:36:0:
./cansam/sam/alignment.h: In constructor ‘sam::alignment::const_iterator::const_iterator(std::iterator<std::forward_iterator_tag, sam::alignment::tagfield, long int, const sam::alignment::tagfield*, const sam::alignment::tagfield&>)’:
./cansam/sam/alignment.h:410:42: error: ‘struct std::iterator<std::forward_iterator_tag, sam::alignment::tagfield, long int, const sam::alignment::tagfield*, const sam::alignment::tagfield&>’ has no member named ‘ptr’
./cansam/sam/alignment.h: In function ‘bool sam::operator==(sam::alignment::iterator, sam::alignment::const_iterator)’:
./cansam/sam/alignment.h:705:41: error: no matching function for call to ‘sam::alignment::const_iterator::const_iterator(sam::alignment::iterator&)’
./cansam/sam/alignment.h:705:41: note: candidates are:
./cansam/sam/alignment.h:432:14: note: sam::alignment::const_iterator::const_iterator(const char*)
./cansam/sam/alignment.h:432:14: note:   no known conversion for argument 1 from ‘sam::alignment::iterator’ to ‘const char*’
./cansam/sam/alignment.h:410:5: note: sam::alignment::const_iterator::const_iterator(std::iterator<std::forward_iterator_tag, sam::alignment::tagfield, long int, const sam::alignment::tagfield*, const sam::alignment::tagfield&>)
./cansam/sam/alignment.h:410:5: note:   no known conversion for argument 1 from ‘sam::alignment::iterator’ to ‘std::iterator<std::forward_iterator_tag, sam::alignment::tagfield, long int, const sam::alignment::tagfield*, const sam::alignment::tagfield&>’
./cansam/sam/alignment.h:409:5: note: sam::alignment::const_iterator::const_iterator(const sam::alignment::const_iterator&)
./cansam/sam/alignment.h:409:5: note:   no known conversion for argument 1 from ‘sam::alignment::iterator’ to ‘const sam::alignment::const_iterator&’
./cansam/sam/alignment.h:408:5: note: sam::alignment::const_iterator::const_iterator()
./cansam/sam/alignment.h:408:5: note:   candidate expects 0 arguments, 1 provided
./cansam/sam/alignment.h: In function ‘bool sam::operator!=(sam::alignment::iterator, sam::alignment::const_iterator)’:
./cansam/sam/alignment.h:707:41: error: no matching function for call to ‘sam::alignment::const_iterator::const_iterator(sam::alignment::iterator&)’
./cansam/sam/alignment.h:707:41: note: candidates are:
./cansam/sam/alignment.h:432:14: note: sam::alignment::const_iterator::const_iterator(const char*)
./cansam/sam/alignment.h:432:14: note:   no known conversion for argument 1 from ‘sam::alignment::iterator’ to ‘const char*’
./cansam/sam/alignment.h:410:5: note: sam::alignment::const_iterator::const_iterator(std::iterator<std::forward_iterator_tag, sam::alignment::tagfield, long int, const sam::alignment::tagfield*, const sam::alignment::tagfield&>)
./cansam/sam/alignment.h:410:5: note:   no known conversion for argument 1 from ‘sam::alignment::iterator’ to ‘std::iterator<std::forward_iterator_tag, sam::alignment::tagfield, long int, const sam::alignment::tagfield*, const sam::alignment::tagfield&>’
./cansam/sam/alignment.h:409:5: note: sam::alignment::const_iterator::const_iterator(const sam::alignment::const_iterator&)
./cansam/sam/alignment.h:409:5: note:   no known conversion for argument 1 from ‘sam::alignment::iterator’ to ‘const sam::alignment::const_iterator&’
./cansam/sam/alignment.h:408:5: note: sam::alignment::const_iterator::const_iterator()
./cansam/sam/alignment.h:408:5: note:   candidate expects 0 arguments, 1 provided
make: *** [lib/alignment.o] Error 1
```

Regards,

Keiran
